apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1 # Specifies that a single Kafka broker pod will be deployed.
  selector:
    matchLabels:
      app: kafka # Ensures the Deployment manages pods with this label.
  template:
    metadata:
      labels:
        app: kafka # The label assigned to the Kafka pod.
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0 # Confluent Kafka Docker image version 7.5.0.
          ports:
            - containerPort: 9092 # Kafka broker listens on port 9092.
          env:
            - name: KAFKA_BROKER_ID
              value: "1" # Unique identifier for this Kafka broker.
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181 # Connects to the Zookeeper service running on port 2181.
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
              # Defines the mapping of listener names to security protocols.
              # PLAINTEXT is used for both internal and external communications.

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092"
              # Specifies the listener addresses to advertise to clients.
              # Internal cluster clients use 'PLAINTEXT://kafka:9092'.
              # External clients use 'PLAINTEXT_HOST://localhost:9092'.

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
              # Specifies the listener used for broker-to-broker communication.

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
              # Number of replicas for the internal Kafka offsets topic.
              # Set to 1 because this is a single-node Kafka setup.
