apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-stream-processor-deployment
  labels:
    app: message-stream-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-stream-processor
  template:
    metadata:
      labels:
        app: message-stream-processor
    spec:
      containers:
        - name: message-stream-processor
          image: message-stream-processor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
