apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment # Name of the deployment for the Spring Boot application.
  labels:
    app: message-stream-processor # Label used to identify this deployment and its associated resources.
spec:
  replicas: 1 # Number of pod replicas to run.
  selector:
    matchLabels:
      app: message-stream-processor # This deployment will manage pods with this label.
  template:
    metadata:
      labels:
        app: message-stream-processor # Label assigned to each pod created by this deployment.
    spec:
      containers:
        - name: message-stream-processor # Name of the container running the Spring Boot app.
          image: message-stream-processor:latest # Docker image for the application.
          ports:
            - containerPort: 8080 # Exposes port 8080 in the container for HTTP traffic.
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "classpath:/,file:/config/"
              # This allows Spring Boot to read configuration files from /config directory in addition to classpath.
              # The ConfigMap containing 'application.properties' will be mounted here.
          volumeMounts:
            - name: kafka-config-volume # Refers to the volume defined below.
              mountPath: /config # Mounts the volume to the /config directory inside the container.
          resources:
            requests:
              cpu: "250m" # Minimum CPU resources requested (0.25 CPU core).
              memory: "256Mi" # Minimum memory requested (256MB).
            limits:
              cpu: "500m" # Maximum CPU resources allowed (0.5 CPU core).
              memory: "512Mi" # Maximum memory allowed (512MB).

      volumes:
        - name: kafka-config-volume # Volume name, linked to a ConfigMap.
          configMap:
            name: kafka-config # References the ConfigMap named 'kafka-config'.
